### ISSUE TITLE
修改密码失败，Exception

### ISSUE THREAD

**Issue by EricSun-Android** [xilibi2003/Upchain-wallet#7]
修改密码时报错，实际修改未成功，抛异常了，小米k20 pro 安卓9.0 
2020-01-16 01:27:10.624 4721-4769/pro.upchain.ethwallet W/System.err: java.io.FileNotFoundException: /data/user/0/pro.upchain.ethwallet/files/keystore_aasd.json/UTC--2020-01-15T17-27-10.6Z--82bd3c6187d458ed1bded14581be6f7e31938071.json (Not a directory)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at java.io.FileOutputStream.open0(Native Method)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at java.io.FileOutputStream.open(FileOutputStream.java:308)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1151)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2997)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at org.web3j.crypto.WalletUtils.generateWalletFile(WalletUtils.java:79)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at pro.upchain.wallet.utils.ETHWalletUtils.modifyPassword(ETHWalletUtils.java:280)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at pro.upchain.wallet.interact.ModifyWalletInteract.lambda$modifyWalletPwd$1(ModifyWalletInteract.java:35)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at pro.upchain.wallet.interact.-$$Lambda$ModifyWalletInteract$ZMZhMnf7tgURLjTjhc2ntZFm0Pk.call(Unknown Source:8)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3575)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-01-16 01:27:10.625 4721-4769/pro.upchain.ethwallet W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-01-16 01:27:10.663 4721-4721/pro.upchain.ethwallet I/Toast: Show toast from OpPackageName:pro.upchain.ethwallet, PackageName:pro.upchain.ethwallet
2020-01-16 01:27:16.177 4721-4754/pro.upchain.ethwallet I/chain.ethwalle: Explicit concurrent copying GC freed 274857(261MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4MB/9MB, paused 85us total 53.855ms

**Comment by fei116fei** [comment]
文件路径错误，已经到web3j的jar封装里了
